// User Login
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const SET_BROWSER_ID = "SET_BROWSER_ID";

// Reset Password
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const USER_REFRESH_RESET_PASSWORD = "USER_REFRESH_RESET_PASSWORD";
